import {
  SingleSignIn,
  SignIn,
  ChangePassword,
  VerifyPhone,
  VerifyOTP,
  VerifyIdentity,
  ResetPassword,
  PasswordUpdated,
  SignUp,
  OnboardingProcess,
  OnboardingHome,
  OnboardingPlatform,
  ProfileHome,
  Design,
  // Jobs,
  Profile,
  // ProfileSettings,
  Billing,
  Privacy,
  // Plan,
  ProfileEdit,
  Asset,
  Activation,
  ContactUs,
  Terms,
  FAQ,
  NotFound,
  EmailChange,
} from '../pages';

export const ROUTES = {
  onboardingProcess: '/process',
  onboardingHome: '/',
  onboardingPlatform: '/platform',
  singleSignIn: '/single_signin',
  signIn: '/signin',
  changePassword: '/access-recovery',
  changeEmail: '/email-change-verification',
  vetifyPhone: '/verify',
  verifyCode: '/verify_code',
  verifyIdentity: '/verify_identity',
  activation: '/email-verification',
  resetPassword: '/reset_password',
  passwordUpdated: '/password_updated',
  signUp: '/signup',
  profileHome: '/profile_home',
  profile: '/profile',
  // profileSettings: '/profile_settings',
  profileEdit: '/profile_edit',
  design: '/design',
  // jobs: '/jobs',
  billing: '/billing',
  // plan: '/plan',
  asset: '/asset/:id',
  assetPage: '/asset',
  contactUs: '/contact_us',
  privacy: '/privacy',
  terms: '/terms',
  faq: '/faq',
  notFound: '*',
};

export const publicRoutes = [
  { name: ROUTES.onboardingProcess, component: <OnboardingProcess /> },
  { name: ROUTES.onboardingHome, component: <OnboardingHome /> },
  { name: ROUTES.onboardingPlatform, component: <OnboardingPlatform /> },
];
export const publicAuthRoutes = [
  { name: ROUTES.changeEmail, component: <EmailChange /> },
];
export const authRoutes = [
  { name: ROUTES.singleSignIn, component: <SingleSignIn /> },
  { name: ROUTES.signIn, component: <SignIn /> },
  { name: ROUTES.changePassword, component: <ChangePassword /> },
  { name: ROUTES.vetifyPhone, component: <VerifyPhone /> },
  { name: ROUTES.verifyCode, component: <VerifyOTP /> },
  { name: ROUTES.activation, component: <Activation /> },
  { name: ROUTES.verifyIdentity, component: <VerifyIdentity /> },
  { name: ROUTES.resetPassword, component: <ResetPassword /> },
  { name: ROUTES.passwordUpdated, component: <PasswordUpdated /> },
  { name: ROUTES.signUp, component: <SignUp /> },
];
export const privateRoutes = [
  { name: ROUTES.profileHome, component: <ProfileHome /> },
  { name: ROUTES.design, component: <Design /> },
  // { name: ROUTES.jobs, component: <Jobs /> },
  { name: ROUTES.profile, component: <Profile /> },
  // { name: ROUTES.profileSettings, component: <ProfileSettings /> },
  { name: ROUTES.profileEdit, component: <ProfileEdit /> },
  { name: ROUTES.billing, component: <Billing /> },
  // { name: ROUTES.plan, component: <Plan /> },
  { name: ROUTES.asset, component: <Asset /> },
  { name: ROUTES.contactUs, component: <ContactUs /> },
];
export const generalRoutes = [
  { name: ROUTES.privacy, component: <Privacy /> },
  { name: ROUTES.terms, component: <Terms /> },
  { name: ROUTES.faq, component: <FAQ /> },
  { name: ROUTES.notFound, component: <NotFound /> },
  // { name: ROUTES.asset, component: <Asset /> },
];
