import {
  uniCard1Gif,
  uniCard3Gif,
  uniCard4Gif,
  uniCard5Gif,
  uniCard6Gif,
  uniCard7Gif,
  uniCard8Gif,
  uniCard9Gif,
  uniCard10Gif,
} from '../assets/gifs';
import {
  university1Img,
  university2Img,
  university3Img,
  uniCard1BigImg,
  uniCard2BigImg,
  uniCard3BigImg,
  uniCard4BigImg,
  uniCard5BigImg,
  uniCard6BigImg,
  uniCard7BigImg,
  uniCard8BigImg,
  uniCard9BigImg,
  uniCard10BigImg,
  uniCard1EmptyImg,
} from '../assets/img';

export const universities = [
  {
    name: 'Cameron Williamson',
    img: university2Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard10BigImg,
    gif: uniCard10Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university1Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard7BigImg,
    gif: uniCard7Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard3BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university2Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard8BigImg,
    gif: uniCard8Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard9BigImg,
    gif: uniCard9Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university1Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard4BigImg,
    gif: uniCard4Gif,
  },
  {
    name: 'Cameron Williamson 2',
    img: university1Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2022',
    bigImg: uniCard1BigImg,
    gif: uniCard1Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard6BigImg,
    gif: uniCard6Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university2Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard5BigImg,
    gif: uniCard5Gif,
  },
];

export const universitiesSlider = [
  {
    name: 'Cameron Williamson',
    img: university1Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard1BigImg,
    gif: uniCard1Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university2Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard2BigImg,
    gif: uniCard1Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard3BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard4BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard5BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard6BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard7BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard8BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard9BigImg,
    gif: uniCard3Gif,
  },
  {
    name: 'Cameron Williamson',
    img: university3Img,
    uniName: 'Stanford University',
    degree: 'Business Administration',
    year: '2020',
    bigImg: uniCard10BigImg,
    gif: uniCard3Gif,
  },
];
export const universitiDesign = {
  name: 'Cameron Williamson',
  img: university1Img,
  uniName: 'Stanford University',
  degree: 'Business Administration',
  year: '2020',
  bigImg: uniCard1EmptyImg,
  gif: uniCard1Gif,
};
